services:
  backend:
    build:
      context: ./packages/backend
      target: development
    ports:
      - '4000:4000'
    volumes:
      - ./packages/backend/src:/app/src
      - ./packages/shared:/app/../shared
    env_file:
      - ./packages/backend/.env
    command: npm run dev
    networks:
      - mubit-network

  frontend:
    build:
      context: ./packages/frontend
      target: development
    ports:
      - '3000:3000'
    volumes:
      - ./packages/frontend/src:/app/src
      - ./packages/frontend/public:/app/public
      - ./packages/shared:/app/../shared
    env_file:
      - ./packages/frontend/.env
    environment:
      - DOCKER=true
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    command: npm run dev
    networks:
      - mubit-network

networks:
  mubit-network:
    driver: bridge
